CREATE TABLE IF NOT EXISTS STAGING.MAIN_EVENT_DTL (
    id BIGINT NOT NULL, -- id
    EVENT_ACTOR VARCHAR(50), -- actor.login
    REPO_UID VARCHAR(30),    -- repo.id
    REPO_NAME VARCHAR(50),   -- repo.name, SHOULD BE TRUNCATED TO 50
    ORG_UID VARCHAR(30),     -- org.id
    ORG_NAME VARCHAR(50),    -- org.login SHOULD BE TRUNCATED TO 50
    CREATION_DATE DATE,   -- created_at
    INSERT_TIME TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP   
);


CREATE TABLE IF NOT EXISTS STAGING.PUSH_EVENT_DTL (
    id BIGINT NOT NULL,
    REPO_ID VARCHAR(50),
    PUSH_ID VARCHAR(50),
    REF VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS STAGING.PULL_EVENT_DTL (
    id BIGINT NOT NULL,
    ACTION_TYPE VARCHAR(50),
    PULL_ID VARCHAR(50),
    PULL_NUM NUMERIC(10),
    REPO_NAME VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS STAGING.ISSUE_EVENT_DTL (
    id BIGINT NOT NULL,
    ACTION_TYPE VARCHAR(50),
    STATUS VARCHAR(15),
    ISSUE_ID VARCHAR(50),
    ISSUE_NUM NUMERIC(10),
    CREATION_DATE DATE,
    CLOSURE_DATE DATE
);