-- ALTER TABLE STAGING.MAIN_EVENT_DTL
-- ADD COLUMN EVENT_TYPE VARCHAR(20);


-- ALTER TABLE STAGING.MAIN_EVENT_DTL
-- ALTER COLUMN id TYPE VARCHAR(50);

-- ALTER TABLE STAGING.MAIN_EVENT_DTL
-- ALTER COLUMN EVENT_TYPE TYPE VARCHAR(30);

ALTER TABLE STAGING.PUSH_EVENT_DTL
ADD COLUMN INSERT_TIME TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;


ALTER TABLE STAGING.PULL_EVENT_DTL
ADD COLUMN INSERT_TIME TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE STAGING.ISSUE_EVENT_DTL
ADD COLUMN INSERT_TIME TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE staging.push_event_dtl RENAME COLUMN repository_id TO repo_id;

